import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Will Scott Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div id="container">
          <h1 className="topleft">Will Scott | <span style={{color: 'hsl(202, 100%, 55%)'}}>Portfolio</span></h1>
          <header><Navbar /></header>
          <hr />
          {children}
          <hr style={{marginTop:'auto'}} />
          <footer>
            <nav>
              <ul>
                {(()=>{
                  let links = {
                    'https://github.com/wscott20': 'GitHub',
                    'https://www.linkedin.com/in/will-scott-6a2718377': 'LinkedIn',
                    '/Resume.pdf': 'Resume',
                  };
                  return Object.entries(links).map(([path, label]) => (
                    <li key={path}>
                      {label == 'Resume' ? <a href={path} download='Resume.pdf'>{label}</a> : <a href={path}>{label}</a>}
                    </li>
                  ));
                })()}
              </ul>
            </nav>
          </footer>
        </div>
      </body>
    </html>
  );
}
